- set_fact: repo_name=app-db
  
- name: install system dependencies
  apt: name={{ item }} state=present
  with_items:
    - mysql-client
    - python-dev
    - libmysqlclient-dev # Yes this is needed in addition to mysql-client

- name: create alembic config
  template: src=alembic.ini.j2 dest=/var/www/appc-db/alembic.ini

- name: install project python dependencies
  pip: requirements=/var/www/{{ repo_name }}/requirements.txt virtualenv=/var/venv/{{ repo_name }}